config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :contracts
  resources :workers
  resources :banks
  resources :oue_organizations
  resources :orders
  resources :perssons
  resources :organizations
  resources :tovars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/bank.rb
class Bank < ApplicationRecord
  belongs_to :oue_organization
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: %i[ show edit update destroy ]

  # GET /banks or /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1 or /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks or /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to bank_url(@bank), notice: "Bank was successfully created." }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1 or /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to bank_url(@bank), notice: "Bank was successfully updated." }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1 or /banks/1.json
  def destroy
    @bank.destroy

    respond_to do |format|
      format.html { redirect_to banks_url, notice: "Bank was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bank_params
      params.require(:bank).permit(:number_caunt_bank, :mfo, :name_and_rquesit_bank, :oue_organization_id)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_bank.html.erb
<div id="<%= dom_id bank %>">
  <p>
    <strong>Number caunt bank:</strong>
    <%= bank.number_caunt_bank %>
  </p>

  <p>
    <strong>Mfo:</strong>
    <%= bank.mfo %>
  </p>

  <p>
    <strong>Name and rquesit bank:</strong>
    <%= bank.name_and_rquesit_bank %>
  </p>

  <p>
    <strong>Oue organization:</strong>
    <%= bank.oue_organization_id %>
  </p>

</div>

app/views/banks/_form.html.erb
<%= form_with(model: bank) do |form| %>
  <% if bank.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
        <% bank.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number_caunt_bank, style: "display: block" %>
    <%= form.text_field :number_caunt_bank %>
  </div>

  <div>
    <%= form.label :mfo, style: "display: block" %>
    <%= form.text_field :mfo %>
  </div>

  <div>
    <%= form.label :name_and_rquesit_bank, style: "display: block" %>
    <%= form.text_field :name_and_rquesit_bank %>
  </div>

  <div>
    <%= form.label :oue_organization_id, style: "display: block" %>
    <%= form.text_field :oue_organization_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<h1>Editing bank</h1>

<%= render "form", bank: @bank %>

<br>

<div>
  <%= link_to "Show this bank", @bank %> |
  <%= link_to "Back to banks", banks_path %>
</div>

app/views/banks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Banks</h1>

<div id="banks">
  <% @banks.each do |bank| %>
    <%= render bank %>
    <p>
      <%= link_to "Show this bank", bank %>
    </p>
  <% end %>
</div>

<%= link_to "New bank", new_bank_path %>

app/views/banks/new.html.erb
<h1>New bank</h1>

<%= render "form", bank: @bank %>

<br>

<div>
  <%= link_to "Back to banks", banks_path %>
</div>

app/views/banks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bank %>

<div>
  <%= link_to "Edit this bank", edit_bank_path(@bank) %> |
  <%= link_to "Back to banks", banks_path %>

  <%= button_to "Destroy this bank", @bank, method: :delete %>
</div>