config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :contracts
  resources :workers
  resources :banks
  resources :oue_organizations
  resources :orders
  resources :perssons
  resources :organizations
  resources :tovars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/oue_organization.rb
class OueOrganization < ApplicationRecord
    has_many :bank
    has_many :worker
end

app/controllers/oue_organizations_controller.rb
class OueOrganizationsController < ApplicationController
  before_action :set_oue_organization, only: %i[ show edit update destroy ]

  # GET /oue_organizations or /oue_organizations.json
  def index
    @oue_organizations = OueOrganization.all
  end

  # GET /oue_organizations/1 or /oue_organizations/1.json
  def show
  end

  # GET /oue_organizations/new
  def new
    @oue_organization = OueOrganization.new
  end

  # GET /oue_organizations/1/edit
  def edit
  end

  # POST /oue_organizations or /oue_organizations.json
  def create
    @oue_organization = OueOrganization.new(oue_organization_params)

    respond_to do |format|
      if @oue_organization.save
        format.html { redirect_to oue_organization_url(@oue_organization), notice: "Oue organization was successfully created." }
        format.json { render :show, status: :created, location: @oue_organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oue_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oue_organizations/1 or /oue_organizations/1.json
  def update
    respond_to do |format|
      if @oue_organization.update(oue_organization_params)
        format.html { redirect_to oue_organization_url(@oue_organization), notice: "Oue organization was successfully updated." }
        format.json { render :show, status: :ok, location: @oue_organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oue_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oue_organizations/1 or /oue_organizations/1.json
  def destroy
    @oue_organization.destroy

    respond_to do |format|
      format.html { redirect_to oue_organizations_url, notice: "Oue organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oue_organization
      @oue_organization = OueOrganization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oue_organization_params
      params.require(:oue_organization).permit(:name, :short_name, :ederpou, :ipn, :type_rent, :adress, :factic_adress, :send_adress, :phone, :mail)
    end
end

app/helpers/oue_organizations_helper.rb
module OueOrganizationsHelper
end

app/views/oue_organizations/_form.html.erb
<%= form_with(model: oue_organization) do |form| %>
  <% if oue_organization.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(oue_organization.errors.count, "error") %> prohibited this oue_organization from being saved:</h2>

      <ul>
        <% oue_organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :short_name, style: "display: block" %>
    <%= form.text_field :short_name %>
  </div>

  <div>
    <%= form.label :ederpou, style: "display: block" %>
    <%= form.text_field :ederpou %>
  </div>

  <div>
    <%= form.label :ipn, style: "display: block" %>
    <%= form.text_field :ipn %>
  </div>

  <div>
    <%= form.label :type_rent, style: "display: block" %>
    <%= form.text_field :type_rent %>
  </div>

  <div>
    <%= form.label :adress, style: "display: block" %>
    <%= form.text_field :adress %>
  </div>

  <div>
    <%= form.label :factic_adress, style: "display: block" %>
    <%= form.text_field :factic_adress %>
  </div>

  <div>
    <%= form.label :send_adress, style: "display: block" %>
    <%= form.text_field :send_adress %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :mail, style: "display: block" %>
    <%= form.text_field :mail %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/oue_organizations/_oue_organization.html.erb
<div id="<%= dom_id oue_organization %>">
  <p>
    <strong>Name:</strong>
    <%= oue_organization.name %>
  </p>

  <p>
    <strong>Short name:</strong>
    <%= oue_organization.short_name %>
  </p>

  <p>
    <strong>Ederpou:</strong>
    <%= oue_organization.ederpou %>
  </p>

  <p>
    <strong>Ipn:</strong>
    <%= oue_organization.ipn %>
  </p>

  <p>
    <strong>Type rent:</strong>
    <%= oue_organization.type_rent %>
  </p>

  <p>
    <strong>Adress:</strong>
    <%= oue_organization.adress %>
  </p>

  <p>
    <strong>Factic adress:</strong>
    <%= oue_organization.factic_adress %>
  </p>

  <p>
    <strong>Send adress:</strong>
    <%= oue_organization.send_adress %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= oue_organization.phone %>
  </p>

  <p>
    <strong>Mail:</strong>
    <%= oue_organization.mail %>
  </p>

</div>

app/views/oue_organizations/edit.html.erb
<h1>Editing oue organization</h1>

<%= render "form", oue_organization: @oue_organization %>

<br>

<div>
  <%= link_to "Show this oue organization", @oue_organization %> |
  <%= link_to "Back to oue organizations", oue_organizations_path %>
</div>

app/views/oue_organizations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Oue organizations</h1>

<div id="oue_organizations">
  <% @oue_organizations.each do |oue_organization| %>
    <%= render oue_organization %>
    <p>
      <%= link_to "Show this oue organization", oue_organization %>
    </p>
  <% end %>
</div>

<%= link_to "New oue organization", new_oue_organization_path %>

app/views/oue_organizations/new.html.erb
<h1>New oue organization</h1>

<%= render "form", oue_organization: @oue_organization %>

<br>

<div>
  <%= link_to "Back to oue organizations", oue_organizations_path %>
</div>

app/views/oue_organizations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @oue_organization %>

<div>
  <%= link_to "Edit this oue organization", edit_oue_organization_path(@oue_organization) %> |
  <%= link_to "Back to oue organizations", oue_organizations_path %>

  <%= button_to "Destroy this oue organization", @oue_organization, method: :delete %>
</div>