config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :contracts
  resources :workers
  resources :banks
  resources :oue_organizations
  resources :orders
  resources :perssons
  resources :organizations
  resources :tovars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/worker.rb
class Worker < ApplicationRecord
    belongs_to :oue_organization
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: %i[ show edit update destroy ]

  # GET /workers or /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1 or /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers or /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to worker_url(@worker), notice: "Worker was successfully created." }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1 or /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to worker_url(@worker), notice: "Worker was successfully updated." }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1 or /workers/1.json
  def destroy
    @worker.destroy

    respond_to do |format|
      format.html { redirect_to workers_url, notice: "Worker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worker_params
      params.require(:worker).permit(:first_name, :last_name, :rather_name, :name_for_contract, :phone, :email, :role)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_with(model: worker) do |form| %>
  <% if worker.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
        <% worker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :rather_name, style: "display: block" %>
    <%= form.text_field :rather_name %>
  </div>

  <div>
    <%= form.label :name_for_contract, style: "display: block" %>
    <%= form.text_field :name_for_contract %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/workers/_worker.html.erb
<div id="<%= dom_id worker %>">
  <p>
    <strong>First name:</strong>
    <%= worker.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= worker.last_name %>
  </p>

  <p>
    <strong>Rather name:</strong>
    <%= worker.rather_name %>
  </p>

  <p>
    <strong>Name for contract:</strong>
    <%= worker.name_for_contract %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= worker.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= worker.email %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= worker.role %>
  </p>

</div>

app/views/workers/edit.html.erb
<h1>Editing worker</h1>

<%= render "form", worker: @worker %>

<br>

<div>
  <%= link_to "Show this worker", @worker %> |
  <%= link_to "Back to workers", workers_path %>
</div>

app/views/workers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Workers</h1>

<div id="workers">
  <% @workers.each do |worker| %>
    <%= render worker %>
    <p>
      <%= link_to "Show this worker", worker %>
    </p>
  <% end %>
</div>

<%= link_to "New worker", new_worker_path %>

app/views/workers/new.html.erb
<h1>New worker</h1>

<%= render "form", worker: @worker %>

<br>

<div>
  <%= link_to "Back to workers", workers_path %>
</div>

app/views/workers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @worker %>

<div>
  <%= link_to "Edit this worker", edit_worker_path(@worker) %> |
  <%= link_to "Back to workers", workers_path %>

  <%= button_to "Destroy this worker", @worker, method: :delete %>
</div>