config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :contracts
  resources :workers
  resources :banks
  resources :oue_organizations
  resources :orders
  resources :perssons
  resources :organizations
  resources :tovars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_many :contract
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[ show edit update destroy ]

  # GET /organizations or /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1 or /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations or /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to organization_url(@organization), notice: "Organization was successfully created." }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1 or /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organization_url(@organization), notice: "Organization was successfully updated." }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1 or /organizations/1.json
  def destroy
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url, notice: "Organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:name, :short_name, :ederpou, :ipn, :type_rent, :adress, :factic_adress, :send_adress, :number_caunt_bank, :mfo, :name_and_rquesit_bank, :phone, :email)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization) do |form| %>
  <% if organization.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :short_name, style: "display: block" %>
    <%= form.text_field :short_name %>
  </div>

  <div>
    <%= form.label :ederpou, style: "display: block" %>
    <%= form.text_field :ederpou %>
  </div>

  <div>
    <%= form.label :ipn, style: "display: block" %>
    <%= form.text_field :ipn %>
  </div>

  <div>
    <%= form.label :type_rent, style: "display: block" %>
    <%= form.text_field :type_rent %>
  </div>

  <div>
    <%= form.label :adress, style: "display: block" %>
    <%= form.text_field :adress %>
  </div>

  <div>
    <%= form.label :factic_adress, style: "display: block" %>
    <%= form.text_field :factic_adress %>
  </div>

  <div>
    <%= form.label :send_adress, style: "display: block" %>
    <%= form.text_field :send_adress %>
  </div>

  <div>
    <%= form.label :number_caunt_bank, style: "display: block" %>
    <%= form.text_field :number_caunt_bank %>
  </div>

  <div>
    <%= form.label :mfo, style: "display: block" %>
    <%= form.text_field :mfo %>
  </div>

  <div>
    <%= form.label :name_and_rquesit_bank, style: "display: block" %>
    <%= form.text_field :name_and_rquesit_bank %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/_organization.html.erb
<div id="<%= dom_id organization %>">
  <p>
    <strong>Name:</strong>
    <%= organization.name %>
  </p>

  <p>
    <strong>Short name:</strong>
    <%= organization.short_name %>
  </p>

  <p>
    <strong>Ederpou:</strong>
    <%= organization.ederpou %>
  </p>

  <p>
    <strong>Ipn:</strong>
    <%= organization.ipn %>
  </p>

  <p>
    <strong>Type rent:</strong>
    <%= organization.type_rent %>
  </p>

  <p>
    <strong>Adress:</strong>
    <%= organization.adress %>
  </p>

  <p>
    <strong>Factic adress:</strong>
    <%= organization.factic_adress %>
  </p>

  <p>
    <strong>Send adress:</strong>
    <%= organization.send_adress %>
  </p>

  <p>
    <strong>Number caunt bank:</strong>
    <%= organization.number_caunt_bank %>
  </p>

  <p>
    <strong>Mfo:</strong>
    <%= organization.mfo %>
  </p>

  <p>
    <strong>Name and rquesit bank:</strong>
    <%= organization.name_and_rquesit_bank %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= organization.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= organization.email %>
  </p>

</div>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render "form", organization: @organization %>

<br>

<div>
  <%= link_to "Show this organization", @organization %> |
  <%= link_to "Back to organizations", organizations_path %>
</div>

app/views/organizations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Organizations</h1>

<div id="organizations">
  <% @organizations.each do |organization| %>
    <%= render organization %>
    <p>
      <%= link_to "Show this organization", organization %>
    </p>
  <% end %>
</div>

<%= link_to "New organization", new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render "form", organization: @organization %>

<br>

<div>
  <%= link_to "Back to organizations", organizations_path %>
</div>

app/views/organizations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @organization %>

<div>
  <%= link_to "Edit this organization", edit_organization_path(@organization) %> |
  <%= link_to "Back to organizations", organizations_path %>

  <%= button_to "Destroy this organization", @organization, method: :delete %>
</div>